export const Images = {
  HEADER_BANNER: {
    LINK: "/Images/Banner.png",
    ALT: "header banner",
  },
  PILOGO_ICON: {
    LINK: "/Images/PiLogoIcon.svg",
    ALT: "pilogoicon",
    HEIGHT: 30,
    WIDTH: 52.72,
  },
  CONTACT_ICON: {
    LINK: "/Images/Avatar.svg",
    ALT: "contacts",
    HEIGHT: 30,
    WIDTH: 30,
  },
  PHONE_ICON: {
    LINK: "/Images/Phone.svg",
    ALT: "phone",
    HEIGHT: 30,
    WIDTH: 30,
  },
  CART_ICON: {
    LINK: "/Images/Cart.svg",
    ALT: "cart",
    HEIGHT: 30,
    WIDTH: 30,
  },
  VECTOR_ICON: {
    LINK: "/Images/Vector.svg",
    ALT: "vector",
  },
  PILOGOTEXT_ICON: {
    LINK: "/Images/PiLogoText.svg",
    ALT: "pilogotext",
    HEIGHT: 30,
    WIDTH: 157,
  },
  TROPHY_ICON: {
    LINK: "/Images/Trophy.svg",
    ALT: "trophy",
  },
  FLASH_ICON: {
    LINK: "/Images/Flash.svg",
    ALT: "flash",
  },
  TICK_ICON: {
    LINK: "/Images/Tick.svg",
    ALT: "Tick",
    HEIGHT: 25,
    WIDTH: 25,
  },
  TIMER_ICON: {
    LINK: "/Images/Timer.svg",
    ALT: "Timer",
    HEIGHT: 24,
    WIDTH: 24,
  },
  MINUTE_ICON: {
    LINK: "/Images/Minute.svg",
    ALT: "Minute",
    HEIGHT: 10,
    WIDTH: 44,
  },
  TWENTY_ICON: {
    LINK: "/Images/20cm.svg",
    ALT: "Twenty",
    HEIGHT: 23,
    WIDTH: 103,
  },
  TEN_ICON: {
    LINK: "/Images/10cm.svg",
    ALT: "Ten",
    HEIGHT: 20,
    WIDTH: 29,
  },
  AREA_ICON: {
    LINK: "/Images/Area.svg",
    ALT: "Area",
    HEIGHT: 21,
    WIDTH: 157,
  },
  CALCULATION_ICON: {
    LINK: "/Images/calculation.svg",
    ALT: "calculation",
    HEIGHT: 180,
    WIDTH: 93,
  },
  CIRCLE_ICON: {
    LINK: "/Images/circle.svg",
    ALT: "circle",
    HEIGHT: 103,
    WIDTH: 103,
  },
  LINE_ICON: {
    LINK: "/Images/Line.png",
    ALT: "Line",
    HEIGHT: 10,
    WIDTH: 44,
  },
  GROUP_ONE: {
    LINK: "/Images/grpone.svg",
    ALT: "Line",
    HEIGHT: 50,
    WIDTH: 124,
  },
  PDF_ICON: {
    LINK: "/Images/PDF.svg",
    ALT: "pdf",
    HEIGHT: 30,
    WIDTH: 30,
  },
  LOCK_ICON: {
    LINK: "/Images/Lock.svg",
    ALT: "lock",
    HEIGHT: 20,
    WIDTH: 17,
  },
  DOWNLOAD_ICON: {
    LINK: "/Images/Download.svg",
    ALT: "download",
    HEIGHT: 50,
    WIDTH: 50,
  },
  PASTPAPER_ICON: {
    LINK: "/Images/PastpaperQuestions.svg",
    ALT: "pastpaper",
    HEIGHT: 50,
    WIDTH: 50,
  },
  SUCCESS_ICON: {
    LINK: "/Images/SuccessRate.svg",
    ALT: "successrate",
    HEIGHT: 50,
    WIDTH: 50,
  },
  SMALLSIZE_ICON: {
    LINK: "/Images/SmallSizeClass.svg",
    ALT: "class",
    HEIGHT: 50,
    WIDTH: 50,
  },
  HERORATING_ICON: {
    LINK: "/Images/herorating.svg",
    ALT: "herorating",
    HEIGHT: 24,
    WIDTH: 132,
  },
  UNION_ICON: {
    LINK: "/Images/Union.svg",
    ALT: "union",
    HEIGHT: 64,
    WIDTH: 64,
  },
  OFF_ICON: {
    LINK: "/Images/70OFF.svg",
    ALT: "off",
    HEIGHT: 64,
    WIDTH: 64,
  },
  FRAME4_ICON: {
    LINK: "/Images/Frame4.png",
    ALT: "frame",
    HEIGHT: 50,
    WIDTH: 50,
  },
  FRAME5_ICON: {
    LINK: "/Images/Frame5.svg",
    ALT: "frame",
    HEIGHT: 50,
    WIDTH: 50,
  },
  FRAME6_ICON: {
    LINK: "/Images/Frame6.svg",
    ALT: "frame",
    HEIGHT: 50,
    WIDTH: 50,
  },
  MATRIC1_ICON: {
    LINK: "/Images/matric1.svg",
    ALT: "matric",
    HEIGHT: 50,
    WIDTH: 50,
  },
  MATRIC2_ICON: {
    LINK: "/Images/matric2.svg",
    ALT: "matric",
    HEIGHT: 50,
    WIDTH: 50,
  },
  FRAME10_ICON: {
    LINK: "/Images/Frame10.png",
    ALT: "frame",
    HEIGHT: 50,
    WIDTH: 50,
  },
  FRAME11_ICON: {
    LINK: "/Images/Frame11.png",
    ALT: "frame",
    HEIGHT: 50,
    WIDTH: 50,
  },
  FRAME13_ICON: {
    LINK: "/Images/Frame13.svg",
    ALT: "frame",
    HEIGHT: 50,
    WIDTH: 50,
  },
  DROPDOWN: {
    LINK: "/Images/Dropdownicon.svg",
    ALT: "dropdown",
    HEIGHT: 7,
    WIDTH: 14,
  },
  QT: {
    LINK: "/Images/qt.svg",
    ALT: "qt",
    HEIGHT: 65,
    WIDTH: 201,
  },
  TALTER: {
    LINK: "/Images/Tatler.svg",
    ALT: "talter",
    HEIGHT: 65,
    WIDTH: 235,
  },
  INSTA_ICON: {
    LINK: "Images/insta.svg",
    ALT: "insta",
    HEIGHT: 30,
    WIDTH: 30,
  },
  FACEBOOK_ICON: {
    LINK: "Images/facebook.svg",
    ALT: "facebook",
    HEIGHT: 30,
    WIDTH: 30,
  },
  TWITTER_ICON: {
    LINK: "Images/Twitter.svg",
    ALT: "twitter",
    HEIGHT: 30,
    WIDTH: 30,
  },
  LINKIDIN_ICON: {
    LINK: "Images/Linkedin.svg",
    ALT: "twitter",
    HEIGHT: 30,
    WIDTH: 30,
  },
  YEAR_ICON: {
    LINK: "Images/Year.svg",
    ALT: "Year",
    HEIGHT: 40,
    WIDTH: 82,
  },
  MSG_ICON: {
    LINK: "Images/msg.svg",
    ALT: "msg",
    HEIGHT: 40,
    WIDTH: 40,
  },
};
